import type { Metadata } from "next";
import "./globals.css";

import { ThemeProvider } from '../context/ThemeContext';
import { FontProvider } from '../context/FontProvider';
import { App } from '../components/App';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <ThemeProvider>
        <FontProvider>
          <App>
            {children}
          </App>
        </FontProvider>
      </ThemeProvider>
    </html>
  );
}
